# -*- coding: utf-8 -*-
"""ideal_v1_patched.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X75muk7ZzQa-9tAMnFKbesZFQ10e5T3t
"""

# Commented out IPython magic to ensure Python compatibility.
from __future__ import annotations

import random
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

# %matplotlib inline



WALL_N: int = 0b0001
WALL_E: int = 0b0010
WALL_S: int = 0b0100
WALL_W: int = 0b1000

DIR_ORDER: List[str] = ["N", "E", "S", "W"]

DIR_BIT: Dict[str, int] = {"N": WALL_N, "E": WALL_E, "S": WALL_S, "W": WALL_W}

OPPOSITE: Dict[str, str] = {"N": "S", "S": "N", "E": "W", "W": "E"}


DELTA: Dict[str, Tuple[int, int]] = {
    "N": (-1, 0),
    "E": (0, 1),
    "S": (1, 0),
    "W": (0, -1),
}


class IllegalMoveError(Exception):
    pass


class Maze:

    def __init__(self, size: int = 16, goal_cells: Optional[Set[Tuple[int, int]]] = None):
        self.size: int = size
        self.walls: np.ndarray = np.zeros((size, size), dtype=np.uint8)
        self.goal_cells: Set[Tuple[int, int]] = goal_cells or self._default_goal_cells()
        self._add_border_walls()


    def _default_goal_cells(self) -> Set[Tuple[int, int]]:

        c = self.size // 2
        if self.size % 2 == 0:
            return {(c - 1, c - 1), (c - 1, c), (c, c - 1), (c, c)}
        return {(c, c)}

    def _add_border_walls(self) -> None:
        for r in range(self.size):
            self.walls[r, 0] |= WALL_W
            self.walls[r, self.size - 1] |= WALL_E
        for c in range(self.size):
            self.walls[0, c] |= WALL_N
            self.walls[self.size - 1, c] |= WALL_S

    def _remove_wall(self, cell: Tuple[int, int], direction: str) -> None:

        r, c = cell
        self.walls[r, c] &= ~DIR_BIT[direction] & 0xF
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.walls[nr, nc] &= ~DIR_BIT[OPPOSITE[direction]] & 0xF

    def set_wall(self, cell: Tuple[int, int], direction: str) -> None:

        r, c = cell
        self.walls[r, c] |= DIR_BIT[direction]
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.walls[nr, nc] |= DIR_BIT[OPPOSITE[direction]]


    def has_wall(self, row: int, col: int, direction: str) -> bool:

        return bool(self.walls[row, col] & DIR_BIT[direction])

    def load_from_matrix(self, matrix) -> None:

        matrix = np.array(matrix, dtype=np.uint8)
        assert matrix.shape[0] == matrix.shape[1], "load_from_matrix: matrix must be square"
        self.walls = matrix.copy()
        self.goal_cells = self._default_goal_cells()

    def generate_random_maze(self, seed: Optional[int] = None, loop_factor: float = 0.03) -> None:

        rng = random.Random(seed)
        size = self.size


        self.walls[:, :] = WALL_N | WALL_E | WALL_S | WALL_W

        start = next(iter(self.goal_cells))
        visited: Set[Tuple[int, int]] = {start}
        stack: List[Tuple[int, int]] = [start]

        while stack:
            cur = stack[-1]
            dirs = DIR_ORDER[:]
            rng.shuffle(dirs)
            carved = False
            for d in dirs:
                dr, dc = DELTA[d]
                nr, nc = cur[0] + dr, cur[1] + dc
                if 0 <= nr < size and 0 <= nc < size and (nr, nc) not in visited:
                    self._remove_wall(cur, d)
                    visited.add((nr, nc))
                    stack.append((nr, nc))
                    carved = True
                    break
            if not carved:
                stack.pop()


        if loop_factor > 0:
            num_extra = max(1, int(loop_factor * size * size))
            for _ in range(num_extra):
                r = rng.randrange(size)
                c = rng.randrange(size)
                d = rng.choice(DIR_ORDER)
                self._remove_wall((r, c), d)


    def visualize(self, ax: Optional[plt.Axes] = None, show: bool = True):

        created_fig = ax is None
        if created_fig:
            fig, ax = plt.subplots(figsize=(5, 5))
        _draw_maze_walls(ax, self)
        if created_fig and show:
            plt.show()
        return ax


def _draw_maze_walls(ax: plt.Axes, maze: Maze) -> None:

    size = maze.size
    ax.set_xlim(0, size)
    ax.set_ylim(0, size)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_xticks([])
    ax.set_yticks([])
    for r in range(size):
        for c in range(size):
            w = maze.walls[r, c]
            x0, y0 = c, r
            if w & WALL_N:
                ax.plot([x0, x0 + 1], [y0, y0], color="black", linewidth=1.5)
            if w & WALL_S:
                ax.plot([x0, x0 + 1], [y0 + 1, y0 + 1], color="black", linewidth=1.5)
            if w & WALL_W:
                ax.plot([x0, x0], [y0, y0 + 1], color="black", linewidth=1.5)
            if w & WALL_E:
                ax.plot([x0 + 1, x0 + 1], [y0, y0 + 1], color="black", linewidth=1.5)
    for (gr, gc) in maze.goal_cells:
        ax.add_patch(plt.Rectangle((gc, gr), 1, 1, color="gold", alpha=0.35, zorder=0))


class FloodFill:


    def __init__(self, size: int, goal_cells: Set[Tuple[int, int]]):
        self.size = size
        self.goal_cells = goal_cells
        self.distances: np.ndarray = np.full((size, size), -1, dtype=int)

    def compute(self, known_walls: np.ndarray) -> np.ndarray:

        size = self.size
        dist = np.full((size, size), -1, dtype=int)
        q: deque = deque()

        for cell in self.goal_cells:
            dist[cell] = 0
            q.append(cell)

        while q:
            r, c = q.popleft()
            d0 = dist[r, c]
            for direction in DIR_ORDER:
                if known_walls[r, c] & DIR_BIT[direction]:
                    continue
                dr, dc = DELTA[direction]
                nr, nc = r + dr, c + dc
                if 0 <= nr < size and 0 <= nc < size and dist[nr, nc] == -1:
                    dist[nr, nc] = d0 + 1
                    q.append((nr, nc))

        self.distances = dist
        return dist



class Micromouse:


    def __init__(
        self,
        maze_size: int,
        start: Tuple[int, int],
        start_heading: str,
        goal_cells: Set[Tuple[int, int]],
    ):
        self.size = maze_size
        self.start = start
        self.position = start
        self.heading = start_heading
        self.goal_cells = goal_cells

        self.visited: Set[Tuple[int, int]] = {start}
        self.known_walls: np.ndarray = np.zeros((maze_size, maze_size), dtype=np.uint8)


        self.history: List[Dict] = [{"position": start, "heading": start_heading}]

        self.mode: str = "exploration"
        self.flood = FloodFill(maze_size, goal_cells)
        self.flood.compute(self.known_walls)


    def _relative_directions(self) -> Dict[str, str]:
        idx = DIR_ORDER.index(self.heading)
        return {
            "front": DIR_ORDER[idx],
            "left": DIR_ORDER[(idx - 1) % 4],
            "right": DIR_ORDER[(idx + 1) % 4],
        }

    def sense_walls(self, true_maze: Maze) -> Dict[str, bool]:

        r, c = self.position
        readings: Dict[str, bool] = {}
        for rel, direction in self._relative_directions().items():
            wall_present = true_maze.has_wall(r, c, direction)
            readings[rel] = wall_present
            if wall_present:
                self._record_wall(direction)
        return readings

    def _record_wall(self, direction: str) -> None:
        r, c = self.position
        self.known_walls[r, c] |= DIR_BIT[direction]
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.known_walls[nr, nc] |= DIR_BIT[OPPOSITE[direction]]


    def turn_left(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx - 1) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_right(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx + 1) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_back(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx + 2) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def move_forward(self) -> None:

        r, c = self.position
        if self.known_walls[r, c] & DIR_BIT[self.heading]:
            raise IllegalMoveError(f"Wall ahead at {self.position} facing {self.heading}")
        dr, dc = DELTA[self.heading]
        nr, nc = r + dr, c + dc
        if not (0 <= nr < self.size and 0 <= nc < self.size):
            raise IllegalMoveError("Attempted to move outside the maze boundary")
        self.position = (nr, nc)
        self.visited.add(self.position)
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_to(self, target_heading: str) -> int:

        if target_heading == self.heading:
            return 0
        idx_cur = DIR_ORDER.index(self.heading)
        idx_tgt = DIR_ORDER.index(target_heading)
        diff = (idx_tgt - idx_cur) % 4
        if diff == 1:
            self.turn_right()
            return 1
        elif diff == 3:
            self.turn_left()
            return 1
        else:  # diff == 2
            self.turn_back()
            return 1



CELL_SIZE_M: float = 0.18       # standard Micromouse cell size (18 cm)
FORWARD_SPEED_MPS: float = 0.5  # assumed cruising speed
TURN_TIME_S: float = 0.15       # assumed time for one 90-degree in-place turn


class Simulator:

    def __init__(
        self,
        maze: Optional[Maze] = None,
        random_maze: bool = True,
        size: int = 16,
        seed: Optional[int] = None,
        start: Tuple[int, int] = None,
        start_heading: str = "N",
        loop_factor: float = 0.03,
    ):
        if maze is not None:
            self.maze = maze
        else:
            self.maze = Maze(size=size)
            if random_maze:
                self.maze.generate_random_maze(seed=seed, loop_factor=loop_factor)

        self.size = self.maze.size
        self.goal_cells = self.maze.goal_cells
        self.start = start if start is not None else (self.size - 1, 0)

        self.mouse = Micromouse(
            maze_size=self.size,
            start=self.start,
            start_heading=start_heading,
            goal_cells=self.goal_cells,
        )

        self.exploration_log: List[Dict] = []
        self.speed_run_log: List[Dict] = []
        self.stats: Dict = {}

    #
    def _choose_next(self, mouse: Micromouse) -> Tuple[Optional[Tuple[int, int]], Optional[str]]:

        r, c = mouse.position
        dist = mouse.flood.distances
        idx_cur = DIR_ORDER.index(mouse.heading)

        best_key = None
        best_cell = None
        best_dir = None

        for direction in DIR_ORDER:
            if mouse.known_walls[r, c] & DIR_BIT[direction]:
                continue
            dr, dc = DELTA[direction]
            nr, nc = r + dr, c + dc
            if not (0 <= nr < self.size and 0 <= nc < self.size):
                continue
            val = dist[nr, nc]
            if val == -1:
                continue

            idx_dir = DIR_ORDER.index(direction)
            turn_cost = (idx_dir - idx_cur) % 4
            turn_cost = min(turn_cost, 4 - turn_cost)

            key = (val, turn_cost)
            if best_key is None or key < best_key:
                best_key = key
                best_cell = (nr, nc)
                best_dir = direction

        return best_cell, best_dir

    def run_exploration(self, max_steps: int = 5000, verbose: bool = True) -> bool:

        mouse = self.mouse
        mouse.mode = "exploration"
        self.exploration_log = [{"position": mouse.position, "heading": mouse.heading}]

        t0 = time.time()
        steps = 0
        while mouse.position not in self.goal_cells and steps < max_steps:
            mouse.sense_walls(self.maze)
            mouse.flood.compute(mouse.known_walls)

            next_cell, direction = self._choose_next(mouse)
            if next_cell is None:
                if verbose:
                    print("Exploration stalled: no reachable move from current known map.")
                break

            mouse.turn_to(direction)
            mouse.move_forward()
            steps += 1
            self.exploration_log.append({"position": mouse.position, "heading": mouse.heading})

            if verbose and steps % 50 == 0:
                print(f"  [exploration] step {steps}: at {mouse.position}")

        t1 = time.time()
        success = mouse.position in self.goal_cells

        self.stats["exploration_steps"] = steps
        self.stats["exploration_time_s"] = t1 - t0
        self.stats["exploration_success"] = success

        if verbose:
            status = "reached goal" if success else "DID NOT reach goal"
            print(f"Exploration finished: {steps} steps, {status}, "
                  f"{t1 - t0:.4f}s compute time.")
        return success


    def compute_shortest_path(self) -> Optional[List[Tuple[int, int]]]:

        walls = self.mouse.known_walls
        start = self.start
        dist = {start: 0}
        prev: Dict[Tuple[int, int], Tuple[int, int]] = {}
        q: deque = deque([start])
        goal_found = None

        while q:
            cur = q.popleft()
            if cur in self.goal_cells:
                goal_found = cur
                break
            r, c = cur
            for direction in DIR_ORDER:
                if walls[r, c] & DIR_BIT[direction]:
                    continue
                dr, dc = DELTA[direction]
                nr, nc = r + dr, c + dc
                if 0 <= nr < self.size and 0 <= nc < self.size and (nr, nc) not in dist:
                    dist[(nr, nc)] = dist[cur] + 1
                    prev[(nr, nc)] = cur
                    q.append((nr, nc))

        if goal_found is None:
            return None

        path = [goal_found]
        while path[-1] != start:
            path.append(prev[path[-1]])
        path.reverse()
        return path

    @staticmethod
    def _direction_between(a: Tuple[int, int], b: Tuple[int, int]) -> str:
        dr, dc = b[0] - a[0], b[1] - a[1]
        for d, (ddr, ddc) in DELTA.items():
            if (ddr, ddc) == (dr, dc):
                return d
        raise ValueError(f"Cells {a} and {b} are not adjacent")

    def run_speed_run(self, verbose: bool = True) -> Optional[List[Tuple[int, int]]]:

        path = self.compute_shortest_path()
        if path is None:
            if verbose:
                print("Speed run aborted: no known path to the goal "
                      "(run_exploration() first).")
            return None

        mouse = self.mouse
        mouse.mode = "speed_run"
        mouse.position = self.start
        mouse.heading = "N"
        self.speed_run_log = [{"position": mouse.position, "heading": mouse.heading}]

        turns = 0
        t0 = time.time()
        for i in range(1, len(path)):
            direction = self._direction_between(path[i - 1], path[i])
            turns += mouse.turn_to(direction)
            mouse.move_forward()
            self.speed_run_log.append({"position": mouse.position, "heading": mouse.heading})
        t1 = time.time()

        path_length = len(path) - 1
        estimated_real_time = (
            path_length * (CELL_SIZE_M / FORWARD_SPEED_MPS) + turns * TURN_TIME_S
        )

        self.stats["speed_run_length"] = path_length
        self.stats["speed_run_turns"] = turns
        self.stats["speed_run_compute_time_s"] = t1 - t0
        self.stats["estimated_real_time_s"] = estimated_real_time

        if verbose:
            print(
                f"Speed run: {path_length} cells, {turns} turns, "
                f"estimated real-world time ~{estimated_real_time:.2f}s "
                f"(assumes {FORWARD_SPEED_MPS} m/s, {CELL_SIZE_M * 100:.0f} cm cells)."
            )
        return path


    def report(self) -> None:
        """Print a human-readable summary of the last exploration + speed run."""
        print("\n===== Simulation Report =====")
        print(f"Maze size:              {self.size} x {self.size}")
        print(f"Exploration steps:      {self.stats.get('exploration_steps')}")
        print(f"Exploration success:    {self.stats.get('exploration_success')}")
        print(f"Shortest-path length:   {self.stats.get('speed_run_length')} cells")
        print(f"Speed-run turns:        {self.stats.get('speed_run_turns')}")
        print(f"Estimated real time:    {self.stats.get('estimated_real_time_s'):.2f} s"
              if self.stats.get('estimated_real_time_s') is not None else
              "Estimated real time:    N/A")
        print("==============================\n")


    def animate(
        self,
        phase: str = "both",
        interval: int = 150,
        show_flood: bool = True,
        save_path: Optional[str] = None,
    ):

        if phase == "exploration":
            frames = self.exploration_log
        elif phase == "speed_run":
            frames = self.speed_run_log
        else:
            frames = self.exploration_log + self.speed_run_log

        if not frames:
            raise RuntimeError("No movement history to animate -- run exploration "
                                "and/or speed run first.")

        final_path = None
        if self.speed_run_log:
            final_path = [f["position"] for f in self.speed_run_log]

        fig, ax = plt.subplots(figsize=(6, 6))

        def render(frame_idx: int):
            ax.clear()
            _draw_maze_walls(ax, self.maze)


            seen = set()
            for step in frames[: frame_idx + 1]:
                seen.add(step["position"])
            for (pr, pc) in seen:
                ax.add_patch(plt.Rectangle((pc, pr), 1, 1, color="lightblue", alpha=0.45, zorder=1))


            if final_path and frame_idx >= len(self.exploration_log) - 1:
                for (pr, pc) in final_path:
                    ax.add_patch(plt.Rectangle((pc, pr), 1, 1, color="limegreen", alpha=0.35, zorder=1))

            if show_flood:
                dist = self.mouse.flood.distances
                for r in range(self.size):
                    for c in range(self.size):
                        if dist[r, c] >= 0:
                            ax.text(c + 0.5, r + 0.5, str(int(dist[r, c])),
                                     fontsize=5, ha="center", va="center", color="gray", zorder=2)

            step = frames[frame_idx]
            pos, heading = step["position"], step["heading"]
            cx, cy = pos[1] + 0.5, pos[0] + 0.5
            ddr, ddc = DELTA[heading]
            ax.arrow(cx, cy, ddc * 0.35, ddr * 0.35, head_width=0.25,
                      head_length=0.2, fc="red", ec="red", zorder=3)

            label = "exploration" if frame_idx < len(self.exploration_log) else "speed run"
            ax.set_title(f"Micromouse [{label}]  step {frame_idx + 1}/{len(frames)}")
            return []

        ani = animation.FuncAnimation(
            fig, render, frames=len(frames), interval=interval, blit=False, repeat=False
        )
        plt.close(fig)

        if save_path:
            ani.save(save_path, writer="pillow")

        try:
            from IPython.display import HTML
            return HTML(ani.to_jshtml())
        except ImportError:
            return ani



class Benchmark:


    def __init__(self, size: int = 16, seed: Optional[int] = None, loop_factor: float = 0.03):
        self.size = size
        self.seed = seed
        self.loop_factor = loop_factor
        self.results: List[Dict] = []

    def run_benchmark(self, num_mazes: int = 100, max_steps: int = 5000, verbose: bool = True) -> Dict:
        rng = random.Random(self.seed)
        successes = 0
        exploration_steps: List[int] = []
        path_lengths: List[int] = []
        total_times: List[float] = []

        for i in range(num_mazes):
            maze_seed = rng.randint(0, 10**9)
            sim = Simulator(random_maze=True, size=self.size, seed=maze_seed,
                             loop_factor=self.loop_factor)

            t0 = time.time()
            ok = sim.run_exploration(max_steps=max_steps, verbose=False)
            if ok:
                sim.run_speed_run(verbose=False)
            t1 = time.time()

            total_times.append(t1 - t0)
            if ok:
                successes += 1
                exploration_steps.append(sim.stats["exploration_steps"])
                if sim.stats.get("speed_run_length") is not None:
                    path_lengths.append(sim.stats["speed_run_length"])

            self.results.append(dict(sim.stats))

            if verbose and (i + 1) % 10 == 0:
                print(f"  [{i + 1}/{num_mazes}] cumulative successes: {successes}")

        summary = {
            "num_mazes": num_mazes,
            "success_rate": successes / num_mazes if num_mazes else 0.0,
            "avg_exploration_steps": float(np.mean(exploration_steps)) if exploration_steps else None,
            "avg_shortest_path_length": float(np.mean(path_lengths)) if path_lengths else None,
            "avg_computation_time_s": float(np.mean(total_times)) if total_times else None,
        }

        print("\n===== Benchmark Summary =====")
        for k, v in summary.items():
            print(f"{k}: {v}")
        print("==============================\n")
        return summary



def get_demo_maze(name: str, size: int = 16) -> Maze:
    if size != 16:
        raise ValueError("get_demo_maze only supports size=16 for now.")
    maze = Maze(size)
    maze.walls[:, :] = WALL_N | WALL_E | WALL_S | WALL_W
    maze._add_border_walls()

    if name == "easy":
        path = [
            (15,0), (14,0), (13,0), (12,0), (11,0), (10,0), (9,0), (8,0),
            (7,0), (7,1), (7,2), (7,3), (7,4), (7,5), (7,6), (7,7)
        ]
    elif name == "medium":
        path = [
            (15,0), (14,0), (13,0), (12,0), (11,0),
            (11,1), (11,2), (11,3), (11,4),
            (10,4), (9,4), (8,4), (7,4),
            (7,5), (7,6), (7,7)
        ]
    elif name == "hard":
        path = [
            (15,0), (14,0), (13,0),
            (13,1), (13,2), (13,3),
            (12,3), (11,3), (10,3), (9,3),
            (9,2), (9,1),
            (8,1), (7,1),
            (7,2), (7,3), (7,4), (7,5), (7,6), (7,7)
        ]
    else:
        raise ValueError(f"Unknown maze name: {name}")

    for i in range(len(path) - 1):
        r1, c1 = path[i]
        r2, c2 = path[i + 1]
        dr = r2 - r1
        dc = c2 - c1
        for d in DIR_ORDER:
            if DELTA[d] == (dr, dc):
                maze._remove_wall((r1, c1), d)
                break
    return maze



MAZE_CHOICES: List[str] = ["random", "easy", "medium", "hard"]


def build_simulator(
    maze_choice: str = "random",
    size: int = 16,
    seed: Optional[int] = None,
    loop_factor: float = 0.03,
) -> Simulator:
    choice = maze_choice.lower().strip()
    if choice not in MAZE_CHOICES:
        raise ValueError(f"Unknown maze_choice {maze_choice!r}; pick one of {MAZE_CHOICES}")

    if choice == "random":
        return Simulator(random_maze=True, size=size, seed=seed, loop_factor=loop_factor)

    maze = get_demo_maze(choice, size=size)
    return Simulator(maze=maze)

maze_choice = "random"  # @param ["random", "easy", "medium", "hard"]
seed = 42

sim = build_simulator(maze_choice, seed=seed)
sim.run_exploration()
sim.run_speed_run()
sim.report()

sim.animate(interval=200)