# -*- coding: utf-8 -*-
"""micromouse_v2_colab (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gKwdZ2v5lfWVtKjA8NCKfki9i820oiSE
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# 0. IMPORTS

from __future__ import annotations

import random
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Set, Tuple

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation



# 1. GLOBAL CONSTANTS -- WALL ENCODING AND DIRECTION MATH


WALL_N: int = 0b0001
WALL_E: int = 0b0010
WALL_S: int = 0b0100
WALL_W: int = 0b1000

DIR_ORDER: List[str] = ["N", "E", "S", "W"]

DIR_BIT: Dict[str, int] = {"N": WALL_N, "E": WALL_E, "S": WALL_S, "W": WALL_W}

OPPOSITE: Dict[str, str] = {"N": "S", "S": "N", "E": "W", "W": "E"}

DELTA: Dict[str, Tuple[int, int]] = {
    "N": (-1, 0),
    "E": (0, 1),
    "S": (1, 0),
    "W": (0, -1),
}


class IllegalMoveError(Exception):
    """Raised when the Micromouse attempts to cross a known wall or leave the maze."""



# 2. MAZE CLASS

class Maze:
    """
    Represents the *ground-truth* Micromouse maze.

    """

    def __init__(self, size: int = 16, goal_cells: Optional[Set[Tuple[int, int]]] = None):
        self.size: int = size
        self.walls: np.ndarray = np.zeros((size, size), dtype=np.uint8)
        self.goal_cells: Set[Tuple[int, int]] = goal_cells or self._default_goal_cells()
        self._add_border_walls()


    def _default_goal_cells(self) -> Set[Tuple[int, int]]:
        """Standard Micromouse goal: the 2x2 block at the maze centre."""
        c = self.size // 2
        if self.size % 2 == 0:
            return {(c - 1, c - 1), (c - 1, c), (c, c - 1), (c, c)}
        return {(c, c)}

    def _add_border_walls(self) -> None:
        for r in range(self.size):
            self.walls[r, 0] |= WALL_W
            self.walls[r, self.size - 1] |= WALL_E
        for c in range(self.size):
            self.walls[0, c] |= WALL_N
            self.walls[self.size - 1, c] |= WALL_S

    def _remove_wall(self, cell: Tuple[int, int], direction: str) -> None:
        """Carve a passage: clears the wall bit on both sides of the edge."""
        r, c = cell
        self.walls[r, c] &= ~DIR_BIT[direction] & 0xF
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.walls[nr, nc] &= ~DIR_BIT[OPPOSITE[direction]] & 0xF

    def set_wall(self, cell: Tuple[int, int], direction: str) -> None:
        """Add a wall on `direction` side of `cell`, mirrored on the neighbour."""
        r, c = cell
        self.walls[r, c] |= DIR_BIT[direction]
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.walls[nr, nc] |= DIR_BIT[OPPOSITE[direction]]


    def has_wall(self, row: int, col: int, direction: str) -> bool:
        """True if there is a wall on `direction` side of cell (row, col)."""
        return bool(self.walls[row, col] & DIR_BIT[direction])

    def load_from_matrix(self, matrix) -> None:
        """Load a maze from an explicit (size x size) wall-bitmask matrix."""
        matrix = np.array(matrix, dtype=np.uint8)
        assert matrix.shape[0] == matrix.shape[1], "Maze matrix must be square."
        self.size = matrix.shape[0]
        self.walls = matrix.copy()
        self.goal_cells = self._default_goal_cells()

    def generate_random_maze(self, seed: Optional[int] = None, loop_factor: float = 0.03) -> None:

        rng = random.Random(seed)
        size = self.size


        self.walls[:, :] = WALL_N | WALL_E | WALL_S | WALL_W

        start = next(iter(self.goal_cells))
        visited: Set[Tuple[int, int]] = {start}
        stack: List[Tuple[int, int]] = [start]

        while stack:
            cur = stack[-1]
            dirs = DIR_ORDER[:]
            rng.shuffle(dirs)
            carved = False
            for d in dirs:
                dr, dc = DELTA[d]
                nr, nc = cur[0] + dr, cur[1] + dc
                if 0 <= nr < size and 0 <= nc < size and (nr, nc) not in visited:
                    self._remove_wall(cur, d)
                    visited.add((nr, nc))
                    stack.append((nr, nc))
                    carved = True
                    break
            if not carved:
                stack.pop()


        if loop_factor > 0:
            num_extra = max(1, int(loop_factor * size * size))
            for _ in range(num_extra):
                r = rng.randrange(size)
                c = rng.randrange(size)
                d = rng.choice(DIR_ORDER)
                self._remove_wall((r, c), d)


    def visualize(self, ax: Optional[plt.Axes] = None, show: bool = True):
        """Quick static plot of the maze walls (no robot)."""
        created_fig = ax is None
        if created_fig:
            fig, ax = plt.subplots(figsize=(5, 5))
        _draw_maze_walls(ax, self)
        if created_fig and show:
            plt.show()
        return ax


def _draw_maze_walls(ax: plt.Axes, maze: Maze) -> None:
    """Shared low-level renderer used by Maze.visualize() and Simulator.animate()."""
    size = maze.size
    ax.set_xlim(0, size)
    ax.set_ylim(0, size)
    ax.set_aspect("equal")
    ax.invert_yaxis()
    ax.set_xticks([])
    ax.set_yticks([])
    for r in range(size):
        for c in range(size):
            w = maze.walls[r, c]
            x0, y0 = c, r
            if w & WALL_N:
                ax.plot([x0, x0 + 1], [y0, y0], color="black", linewidth=1.5)
            if w & WALL_S:
                ax.plot([x0, x0 + 1], [y0 + 1, y0 + 1], color="black", linewidth=1.5)
            if w & WALL_W:
                ax.plot([x0, x0], [y0, y0 + 1], color="black", linewidth=1.5)
            if w & WALL_E:
                ax.plot([x0 + 1, x0 + 1], [y0, y0 + 1], color="black", linewidth=1.5)
    for (gr, gc) in maze.goal_cells:
        ax.add_patch(plt.Rectangle((gc, gr), 1, 1, color="gold", alpha=0.35, zorder=0))



# 3. FLOOD FILL ALGORITHM

class FloodFill:


    def __init__(self, size: int, goal_cells: Set[Tuple[int, int]]):
        self.size = size
        self.goal_cells = goal_cells
        self.distances: np.ndarray = np.full((size, size), -1, dtype=int)

    def compute(self, known_walls: np.ndarray) -> np.ndarray:
        """Recompute the full distance map via multi-source BFS from the goal
        cells, using only the walls the robot currently knows about."""
        size = self.size
        dist = np.full((size, size), -1, dtype=int)
        q: deque = deque()

        for cell in self.goal_cells:
            dist[cell] = 0
            q.append(cell)

        while q:
            r, c = q.popleft()
            d0 = dist[r, c]
            for direction in DIR_ORDER:
                if known_walls[r, c] & DIR_BIT[direction]:
                    continue
                dr, dc = DELTA[direction]
                nr, nc = r + dr, c + dc
                if 0 <= nr < size and 0 <= nc < size and dist[nr, nc] == -1:
                    dist[nr, nc] = d0 + 1
                    q.append((nr, nc))

        self.distances = dist
        return dist



# 4. MICROMOUSE CLASS (robot state + movement primitives + virtual sensors)

class Micromouse:


    def __init__(
        self,
        maze_size: int,
        start: Tuple[int, int],
        start_heading: str,
        goal_cells: Set[Tuple[int, int]],
    ):
        self.size = maze_size
        self.start = start
        self.position = start
        self.heading = start_heading
        self.goal_cells = goal_cells

        self.visited: Set[Tuple[int, int]] = {start}
        self.known_walls: np.ndarray = np.zeros((maze_size, maze_size), dtype=np.uint8)


        self.history: List[Dict] = [{"position": start, "heading": start_heading}]

        self.mode: str = "exploration"
        self.flood = FloodFill(maze_size, goal_cells)
        self.flood.compute(self.known_walls)


    def _relative_directions(self) -> Dict[str, str]:
        idx = DIR_ORDER.index(self.heading)
        return {
            "front": DIR_ORDER[idx],
            "left": DIR_ORDER[(idx - 1) % 4],
            "right": DIR_ORDER[(idx + 1) % 4],
        }

    def sense_walls(self, true_maze: Maze) -> Dict[str, bool]:

        r, c = self.position
        readings: Dict[str, bool] = {}
        for rel, direction in self._relative_directions().items():
            wall_present = true_maze.has_wall(r, c, direction)
            readings[rel] = wall_present
            if wall_present:
                self._record_wall(direction)
        return readings

    def _record_wall(self, direction: str) -> None:
        r, c = self.position
        self.known_walls[r, c] |= DIR_BIT[direction]
        dr, dc = DELTA[direction]
        nr, nc = r + dr, c + dc
        if 0 <= nr < self.size and 0 <= nc < self.size:
            self.known_walls[nr, nc] |= DIR_BIT[OPPOSITE[direction]]


    def turn_left(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx - 1) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_right(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx + 1) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_back(self) -> None:
        idx = DIR_ORDER.index(self.heading)
        self.heading = DIR_ORDER[(idx + 2) % 4]
        self.history.append({"position": self.position, "heading": self.heading})

    def move_forward(self) -> None:
        """Move one cell in the current heading. Raises IllegalMoveError if a
        known wall or the maze boundary blocks the path."""
        r, c = self.position
        if self.known_walls[r, c] & DIR_BIT[self.heading]:
            raise IllegalMoveError(f"Wall ahead at {self.position} facing {self.heading}")
        dr, dc = DELTA[self.heading]
        nr, nc = r + dr, c + dc
        if not (0 <= nr < self.size and 0 <= nc < self.size):
            raise IllegalMoveError("Attempted to move outside the maze boundary")
        self.position = (nr, nc)
        self.visited.add(self.position)
        self.history.append({"position": self.position, "heading": self.heading})

    def turn_to(self, target_heading: str) -> int:

        if target_heading == self.heading:
            return 0
        idx_cur = DIR_ORDER.index(self.heading)
        idx_tgt = DIR_ORDER.index(target_heading)
        diff = (idx_tgt - idx_cur) % 4
        if diff == 1:
            self.turn_right()
            return 1
        elif diff == 3:
            self.turn_left()
            return 1
        else:  # diff == 2
            self.turn_back()
            return 1



# 5. SIMULATOR CLASS (orchestrates exploration, speed run, visualization)

CELL_SIZE_M: float = 0.18       # standard Micromouse cell size (18 cm)
CELL_SIZE_MM: float = CELL_SIZE_M * 1000.0
FORWARD_SPEED_MPS: float = 0.5  # assumed cruising speed
TURN_TIME_S: float = 0.15       # assumed time for one 90-degree in-place turn


class Simulator:
    """High-level API that ties Maze + Micromouse + FloodFill together and
    drives the exploration / speed-run / visualization workflow."""

    def __init__(
        self,
        maze: Optional[Maze] = None,
        random_maze: bool = True,
        size: int = 16,
        seed: Optional[int] = None,
        start: Tuple[int, int] = None,
        start_heading: str = "N",
        loop_factor: float = 0.03,
        physics: bool = False,
        physics_seed: Optional[int] = None,
        sensor_sigma_mm: float = 6.0,
        robot_radius_mm: float = 40.0,
        drive_config: Optional["DifferentialDriveConfig"] = None,
        dt_s: float = 0.01,
    ):
        if maze is not None:
            self.maze = maze
        else:
            self.maze = Maze(size=size)
            if random_maze:
                self.maze.generate_random_maze(seed=seed, loop_factor=loop_factor)

        self.size = self.maze.size
        self.goal_cells = self.maze.goal_cells
        self.start = start if start is not None else (self.size - 1, 0)
        self.physics_enabled = physics

        if physics:

            self.mouse: Micromouse = NoisyMicromouse(
                maze_size=self.size,
                start=self.start,
                start_heading=start_heading,
                goal_cells=self.goal_cells,
                drive_config=drive_config,
                sensor_sigma_mm=sensor_sigma_mm,
                robot_radius_mm=robot_radius_mm,
                dt_s=dt_s,
                seed=physics_seed,
            )
            self.mouse.true_maze = self.maze
        else:
            self.mouse = Micromouse(
                maze_size=self.size,
                start=self.start,
                start_heading=start_heading,
                goal_cells=self.goal_cells,
            )

        self.exploration_log: List[Dict] = []
        self.speed_run_log: List[Dict] = []
        self.stats: Dict = {}

    # ------------------------------------------------------------ exploration
    def _choose_next(self, mouse: Micromouse) -> Tuple[Optional[Tuple[int, int]], Optional[str]]:

        r, c = mouse.position
        dist = mouse.flood.distances
        idx_cur = DIR_ORDER.index(mouse.heading)

        best_key = None
        best_cell = None
        best_dir = None

        for direction in DIR_ORDER:
            if mouse.known_walls[r, c] & DIR_BIT[direction]:
                continue
            dr, dc = DELTA[direction]
            nr, nc = r + dr, c + dc
            if not (0 <= nr < self.size and 0 <= nc < self.size):
                continue
            val = dist[nr, nc]
            if val == -1:
                continue

            idx_dir = DIR_ORDER.index(direction)
            turn_cost = (idx_dir - idx_cur) % 4
            turn_cost = min(turn_cost, 4 - turn_cost)

            key = (val, turn_cost)
            if best_key is None or key < best_key:
                best_key = key
                best_cell = (nr, nc)
                best_dir = direction

        return best_cell, best_dir

    def run_exploration(self, max_steps: int = 5000, verbose: bool = True) -> bool:

        mouse = self.mouse
        mouse.mode = "exploration"
        self.exploration_log = [{"position": mouse.position, "heading": mouse.heading}]

        t0 = time.time()
        steps = 0
        while mouse.position not in self.goal_cells and steps < max_steps:
            mouse.sense_walls(self.maze)
            mouse.flood.compute(mouse.known_walls)

            next_cell, direction = self._choose_next(mouse)
            if next_cell is None:
                if verbose:
                    print("Exploration stalled: no reachable move from current known map.")
                break

            mouse.turn_to(direction)
            mouse.move_forward()
            steps += 1
            self.exploration_log.append({"position": mouse.position, "heading": mouse.heading})

            if verbose and steps % 50 == 0:
                print(f"  [exploration] step {steps}: at {mouse.position}")

        t1 = time.time()
        success = mouse.position in self.goal_cells

        self.stats["exploration_steps"] = steps
        self.stats["exploration_time_s"] = t1 - t0
        self.stats["exploration_success"] = success

        if verbose:
            status = "reached goal" if success else "DID NOT reach goal"
            print(f"Exploration finished: {steps} steps, {status}, "
                  f"{t1 - t0:.4f}s compute time.")
        return success

    # -------------------------------------------------------------- speed run
    def compute_shortest_path(self) -> Optional[List[Tuple[int, int]]]:
        """BFS shortest path from the start cell to a goal cell using the
        mouse's *currently known* wall map."""
        walls = self.mouse.known_walls
        start = self.start
        dist = {start: 0}
        prev: Dict[Tuple[int, int], Tuple[int, int]] = {}
        q: deque = deque([start])
        goal_found = None

        while q:
            cur = q.popleft()
            if cur in self.goal_cells:
                goal_found = cur
                break
            r, c = cur
            for direction in DIR_ORDER:
                if walls[r, c] & DIR_BIT[direction]:
                    continue
                dr, dc = DELTA[direction]
                nr, nc = r + dr, c + dc
                if 0 <= nr < self.size and 0 <= nc < self.size and (nr, nc) not in dist:
                    dist[(nr, nc)] = dist[cur] + 1
                    prev[(nr, nc)] = cur
                    q.append((nr, nc))

        if goal_found is None:
            return None

        path = [goal_found]
        while path[-1] != start:
            path.append(prev[path[-1]])
        path.reverse()
        return path

    @staticmethod
    def _direction_between(a: Tuple[int, int], b: Tuple[int, int]) -> str:
        dr, dc = b[0] - a[0], b[1] - a[1]
        for d, (ddr, ddc) in DELTA.items():
            if (ddr, ddc) == (dr, dc):
                return d
        raise ValueError(f"Cells {a} and {b} are not adjacent")

    def run_speed_run(self, verbose: bool = True) -> Optional[List[Tuple[int, int]]]:

        path = self.compute_shortest_path()
        if path is None:
            if verbose:
                print("Speed run aborted: no known path to the goal "
                      "(run_exploration() first).")
            return None

        mouse = self.mouse
        mouse.mode = "speed_run"
        mouse.position = self.start
        mouse.heading = "N"
        self.speed_run_log = [{"position": mouse.position, "heading": mouse.heading}]

        turns = 0
        t0 = time.time()
        for i in range(1, len(path)):
            direction = self._direction_between(path[i - 1], path[i])
            turns += mouse.turn_to(direction)
            mouse.move_forward()
            self.speed_run_log.append({"position": mouse.position, "heading": mouse.heading})
        t1 = time.time()

        path_length = len(path) - 1  # number of cell-to-cell moves
        estimated_real_time = (
            path_length * (CELL_SIZE_M / FORWARD_SPEED_MPS) + turns * TURN_TIME_S
        )

        self.stats["speed_run_length"] = path_length
        self.stats["speed_run_turns"] = turns
        self.stats["speed_run_compute_time_s"] = t1 - t0
        self.stats["estimated_real_time_s"] = estimated_real_time

        if verbose:
            print(
                f"Speed run: {path_length} cells, {turns} turns, "
                f"estimated real-world time ~{estimated_real_time:.2f}s "
                f"(assumes {FORWARD_SPEED_MPS} m/s, {CELL_SIZE_M * 100:.0f} cm cells)."
            )
        return path


    def report(self) -> None:
        """Print a human-readable summary of the last exploration + speed run."""
        print("\n===== Simulation Report =====")
        print(f"Maze size:              {self.size} x {self.size}")
        print(f"Exploration steps:      {self.stats.get('exploration_steps')}")
        print(f"Exploration success:    {self.stats.get('exploration_success')}")
        print(f"Shortest-path length:   {self.stats.get('speed_run_length')} cells")
        print(f"Speed-run turns:        {self.stats.get('speed_run_turns')}")
        print(f"Estimated real time:    {self.stats.get('estimated_real_time_s'):.2f} s"
              if self.stats.get('estimated_real_time_s') is not None else
              "Estimated real time:    N/A")
        if self.physics_enabled and isinstance(self.mouse, NoisyMicromouse):
            drifts = [abs(d["lateral_drift_mm"]) for d in self.mouse.drift_log if "lateral_drift_mm" in d]
            heads = [abs(d["heading_error_deg"]) for d in self.mouse.drift_log if "heading_error_deg" in d]
            print("---- Version 2 physics stats ----")
            print(f"Avg position drift:     {np.mean(drifts):.2f} mm" if drifts else "Avg position drift:     N/A")
            print(f"Avg heading error:      {np.mean(heads):.2f} deg" if heads else "Avg heading error:      N/A")
            print(f"Collisions detected:    {self.mouse.collision_count}")
        print("==============================\n")


    def animate(
        self,
        phase: str = "both",
        interval: int = 150,
        show_flood: bool = True,
        save_path: Optional[str] = None,
    ):
        """
        phase: 'exploration' | 'speed_run' | 'both'
        """
        if phase == "exploration":
            frames = self.exploration_log
        elif phase == "speed_run":
            frames = self.speed_run_log
        else:
            frames = self.exploration_log + self.speed_run_log

        if not frames:
            raise RuntimeError("No movement history to animate -- run exploration "
                                "and/or speed run first.")

        final_path = None
        if self.speed_run_log:
            final_path = [f["position"] for f in self.speed_run_log]

        fig, ax = plt.subplots(figsize=(6, 6))

        def render(frame_idx: int):
            ax.clear()
            _draw_maze_walls(ax, self.maze)


            seen = set()
            for step in frames[: frame_idx + 1]:
                seen.add(step["position"])
            for (pr, pc) in seen:
                ax.add_patch(plt.Rectangle((pc, pr), 1, 1, color="lightblue", alpha=0.45, zorder=1))


            if final_path and frame_idx >= len(self.exploration_log) - 1:
                for (pr, pc) in final_path:
                    ax.add_patch(plt.Rectangle((pc, pr), 1, 1, color="limegreen", alpha=0.35, zorder=1))

            if show_flood:
                dist = self.mouse.flood.distances
                for r in range(self.size):
                    for c in range(self.size):
                        if dist[r, c] >= 0:
                            ax.text(c + 0.5, r + 0.5, str(int(dist[r, c])),
                                     fontsize=5, ha="center", va="center", color="gray", zorder=2)

            step = frames[frame_idx]
            pos, heading = step["position"], step["heading"]
            cx, cy = pos[1] + 0.5, pos[0] + 0.5
            ddr, ddc = DELTA[heading]
            ax.arrow(cx, cy, ddc * 0.35, ddr * 0.35, head_width=0.25,
                      head_length=0.2, fc="red", ec="red", zorder=3)

            label = "exploration" if frame_idx < len(self.exploration_log) else "speed run"
            ax.set_title(f"Micromouse [{label}]  step {frame_idx + 1}/{len(frames)}")
            return []

        ani = animation.FuncAnimation(
            fig, render, frames=len(frames), interval=interval, blit=False, repeat=False
        )
        plt.close(fig)

        if save_path:
            ani.save(save_path, writer="pillow")

        try:
            from IPython.display import HTML
            return HTML(ani.to_jshtml())
        except ImportError:
            return ani


# 6. BENCHMARK CLASS (validation framework)

class Benchmark:


    def __init__(self, size: int = 16, seed: Optional[int] = None, loop_factor: float = 0.03):
        self.size = size
        self.seed = seed
        self.loop_factor = loop_factor
        self.results: List[Dict] = []

    def run_benchmark(self, num_mazes: int = 100, max_steps: int = 5000, verbose: bool = True) -> Dict:
        rng = random.Random(self.seed)
        successes = 0
        exploration_steps: List[int] = []
        path_lengths: List[int] = []
        total_times: List[float] = []

        for i in range(num_mazes):
            maze_seed = rng.randint(0, 10**9)
            sim = Simulator(random_maze=True, size=self.size, seed=maze_seed,
                             loop_factor=self.loop_factor)

            t0 = time.time()
            ok = sim.run_exploration(max_steps=max_steps, verbose=False)
            if ok:
                sim.run_speed_run(verbose=False)
            t1 = time.time()

            total_times.append(t1 - t0)
            if ok:
                successes += 1
                exploration_steps.append(sim.stats["exploration_steps"])
                if sim.stats.get("speed_run_length") is not None:
                    path_lengths.append(sim.stats["speed_run_length"])

            self.results.append(dict(sim.stats))

            if verbose and (i + 1) % 10 == 0:
                print(f"  [{i + 1}/{num_mazes}] cumulative successes: {successes}")

        summary = {
            "num_mazes": num_mazes,
            "success_rate": successes / num_mazes if num_mazes else 0.0,
            "avg_exploration_steps": float(np.mean(exploration_steps)) if exploration_steps else None,
            "avg_shortest_path_length": float(np.mean(path_lengths)) if path_lengths else None,
            "avg_computation_time_s": float(np.mean(total_times)) if total_times else None,
        }

        print("\n===== Benchmark Summary =====")
        for k, v in summary.items():
            print(f"{k}: {v}")
        print("==============================\n")
        return summary



import math



# 8. CONTINUOUS POSE & DIFFERENTIAL-DRIVE KINEMATICS

HEADING_TO_THETA_DEG: Dict[str, float] = {"E": 0.0, "S": 90.0, "W": 180.0, "N": 270.0}


WALL_FOLLOW_TARGET_MM: float = CELL_SIZE_MM / 2.0


@dataclass
class RobotPose:
    """Continuous robot pose in millimetres / radians (world frame)."""
    x_mm: float
    y_mm: float
    theta_rad: float


def pose_for_cell(row: int, col: int, heading: str, cell_size_mm: float = CELL_SIZE_MM) -> RobotPose:

    return RobotPose(
        x_mm=(col + 0.5) * cell_size_mm,
        y_mm=(row + 0.5) * cell_size_mm,
        theta_rad=math.radians(HEADING_TO_THETA_DEG[heading]),
    )


def _wrap_angle(angle_rad: float) -> float:
    """Wrap an angle (radians) to (-pi, pi]."""
    return (angle_rad + math.pi) % (2 * math.pi) - math.pi


def _clip(value: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, value))


def _trapezoidal_profile(n_steps: int, total: float, dt: float) -> List[float]:

    ramp = max(1, n_steps // 4)
    cruise = max(0, n_steps - 2 * ramp)
    shape = [(i + 1) / ramp for i in range(ramp)] + [1.0] * cruise + [(ramp - i) / ramp for i in range(ramp)]
    shape = (shape + [1.0] * n_steps)[:n_steps]
    shape_sum = sum(shape) if sum(shape) > 0 else 1.0
    scale = total / (dt * shape_sum)
    return [s * scale for s in shape]


def _point_to_line_distance(px: float, py: float, x1: float, y1: float, x2: float, y2: float) -> float:
    """Perpendicular distance from point (px,py) to the line through (x1,y1)-(x2,y2)."""
    dx, dy = x2 - x1, y2 - y1
    length = math.hypot(dx, dy)
    if length < 1e-9:
        return math.hypot(px - x1, py - y1)
    return abs(dy * px - dx * py + x2 * y1 - y2 * x1) / length


@dataclass
class DifferentialDriveConfig:

    wheel_radius_mm: float = 15.0
    wheelbase_mm: float = 80.0
    ticks_per_rev: int = 360
    max_speed_mm_s: float = 500.0
    max_omega_rad_s: float = math.radians(400.0)
    omega_noise_std: float = 0.05


class DifferentialDrive:
    """
        v_left  = v - omega * wheelbase / 2
        v_right = v + omega * wheelbase / 2
        wheel_angular_speed = v_wheel / wheel_radius
    """

    def __init__(self, config: Optional[DifferentialDriveConfig] = None):
        self.config = config or DifferentialDriveConfig()

    @property
    def max_speed_mm_s(self) -> float:
        return self.config.max_speed_mm_s

    @property
    def max_omega_rad_s(self) -> float:
        return self.config.max_omega_rad_s

    @property
    def omega_noise_std(self) -> float:
        return self.config.omega_noise_std

    def wheel_angular_speeds(self, v_mm_s: float, omega_rad_s: float) -> Tuple[float, float]:
        """Inverse kinematics: body (v, omega) -> (left, right) wheel angular speed in rad/s."""
        half_wb = self.config.wheelbase_mm / 2.0
        v_left = v_mm_s - omega_rad_s * half_wb
        v_right = v_mm_s + omega_rad_s * half_wb
        return v_left / self.config.wheel_radius_mm, v_right / self.config.wheel_radius_mm

    def ticks_for(self, wheel_angular_speed_rad_s: float, dt: float) -> float:
        """Simulated encoder tick count accumulated over `dt` at the given
        wheel angular speed (fractional -- callers accumulate and may round
        when reading the 'hardware' counter)."""
        revolutions = wheel_angular_speed_rad_s * dt / (2 * math.pi)
        return revolutions * self.config.ticks_per_rev



# 9. NOISY SENSOR MODEL (RAYCASTING + GAUSSIAN NOISE)
def raycast_distance_mm(
    x_mm: float, y_mm: float, angle_rad: float, maze: Maze,
    cell_size_mm: float = CELL_SIZE_MM, max_range_mm: float = 250.0, step_mm: float = 3.0,
) -> float:
    """
    Approximate ray-marching distance sensor model: steps a ray outward from
    (x_mm, y_mm) at `angle_rad` in small increments, and returns the distance
    at which it first crosses a maze wall (or `max_range_mm` if none found).

    """
    dx, dy = math.cos(angle_rad), math.sin(angle_rad)
    prev_row, prev_col = int(y_mm // cell_size_mm), int(x_mm // cell_size_mm)
    steps = int(max_range_mm / step_mm)
    for i in range(1, steps + 1):
        d = i * step_mm
        x, y = x_mm + dx * d, y_mm + dy * d
        row, col = int(y // cell_size_mm), int(x // cell_size_mm)
        if not (0 <= row < maze.size and 0 <= col < maze.size):
            return d
        if row != prev_row or col != prev_col:
            if col > prev_col and maze.has_wall(prev_row, prev_col, "E"):
                return d
            if col < prev_col and maze.has_wall(prev_row, prev_col, "W"):
                return d
            if row > prev_row and maze.has_wall(prev_row, prev_col, "S"):
                return d
            if row < prev_row and maze.has_wall(prev_row, prev_col, "N"):
                return d
            prev_row, prev_col = row, col
    return max_range_mm


@dataclass
class NoisySensorArray:
    """Simulates the three physical IR wall sensors (front/left/right) with
    additive Gaussian noise on the raw distance reading, then thresholds
    each into a boolean wall/no-wall decision -- exactly mirroring how a
    real sensor's analog reading is thresholded in firmware."""
    sigma_mm: float = 6.0
    wall_threshold_mm: float = 110.0
    max_range_mm: float = 250.0
    rng: random.Random = field(default_factory=random.Random)

    def _noisy(self, true_mm: float) -> float:
        reading = true_mm + self.rng.gauss(0.0, self.sigma_mm)
        return _clip(reading, 0.0, self.max_range_mm)

    def read(self, pose: RobotPose, maze: Maze, cell_size_mm: float = CELL_SIZE_MM) -> Dict:
        theta = pose.theta_rad
        front_true = raycast_distance_mm(pose.x_mm, pose.y_mm, theta, maze, cell_size_mm, self.max_range_mm)
        left_true = raycast_distance_mm(pose.x_mm, pose.y_mm, theta - math.pi / 2, maze, cell_size_mm, self.max_range_mm)
        right_true = raycast_distance_mm(pose.x_mm, pose.y_mm, theta + math.pi / 2, maze, cell_size_mm, self.max_range_mm)

        f, l, r = self._noisy(front_true), self._noisy(left_true), self._noisy(right_true)
        return {
            "front_dist": f, "left_dist": l, "right_dist": r,
            "front_wall": f < self.wall_threshold_mm,
            "left_wall": l < self.wall_threshold_mm,
            "right_wall": r < self.wall_threshold_mm,
        }


def _lateral_wall_error(reading: Dict) -> float:
    """Wall-following error signal for the PID controller: positive means
    the robot is closer to the left wall than the right (should steer
    right), using whichever side sensor(s) currently see a wall."""
    if reading["left_wall"] and reading["right_wall"]:
        return reading["right_dist"] - reading["left_dist"]
    if reading["left_wall"]:
        return WALL_FOLLOW_TARGET_MM - reading["left_dist"]
    if reading["right_wall"]:
        return -(WALL_FOLLOW_TARGET_MM - reading["right_dist"])
    return 0.0



# 10. PID CONTROLLER

class PIDController:


    def __init__(self, kp: float, ki: float, kd: float, output_limit: Optional[float] = None):
        self.kp, self.ki, self.kd = kp, ki, kd
        self.output_limit = output_limit
        self.reset()

    def reset(self) -> None:
        self._integral = 0.0
        self._prev_error: Optional[float] = None

    def update(self, error: float, dt: float) -> float:
        self._integral += error * dt
        derivative = 0.0 if self._prev_error is None else (error - self._prev_error) / dt
        self._prev_error = error
        output = self.kp * error + self.ki * self._integral + self.kd * derivative
        if self.output_limit is not None:
            output = _clip(output, -self.output_limit, self.output_limit)
        return output


# 11. ROBOT PHYSICS ENGINE

class RobotPhysics:


    def __init__(
        self,
        pose: RobotPose,
        drive: Optional[DifferentialDrive] = None,
        sensors: Optional[NoisySensorArray] = None,
        robot_radius_mm: float = 40.0,
        dt_s: float = 0.01,
        rng: Optional[random.Random] = None,
    ):
        self.pose = pose
        self.drive = drive or DifferentialDrive()
        self.rng = rng or random.Random()
        self.sensors = sensors or NoisySensorArray(rng=self.rng)
        self.robot_radius_mm = robot_radius_mm
        self.dt = dt_s

        self.total_left_ticks: float = 0.0
        self.total_right_ticks: float = 0.0
        self.collisions: int = 0


    def _check_collision(self, maze: Maze, cell_size_mm: float) -> bool:
        """True if the robot's circular footprint has crossed into a wall."""
        col = int(self.pose.x_mm // cell_size_mm)
        row = int(self.pose.y_mm // cell_size_mm)
        if not (0 <= row < maze.size and 0 <= col < maze.size):
            return True
        fx = self.pose.x_mm - col * cell_size_mm
        fy = self.pose.y_mm - row * cell_size_mm
        r = self.robot_radius_mm
        if fx < r and maze.has_wall(row, col, "W"):
            return True
        if cell_size_mm - fx < r and maze.has_wall(row, col, "E"):
            return True
        if fy < r and maze.has_wall(row, col, "N"):
            return True
        if cell_size_mm - fy < r and maze.has_wall(row, col, "S"):
            return True
        return False

    def forward_one_cell_physics(
        self, maze: Maze, target_heading: str, cell_size_mm: float = CELL_SIZE_MM,
        n_steps: int = 40, pid: Optional[PIDController] = None,
    ) -> Dict:
        """
        Drive forward exactly one cell length using a trapezoidal
        acceleration/cruise/deceleration speed profile, correcting heading
        with a PID wall-follower fed by noisy side-sensor readings.

        """
        theta_target = math.radians(HEADING_TO_THETA_DEG[target_heading])
        pid = pid or PIDController(kp=0.02, ki=0.0008, kd=0.012, output_limit=self.drive.max_omega_rad_s)
        pid.reset()

        start_x, start_y = self.pose.x_mm, self.pose.y_mm
        speed_profile = _trapezoidal_profile(n_steps, cell_size_mm, self.dt)
        collided = False

        for v in speed_profile:
            reading = self.sensors.read(self.pose, maze, cell_size_mm)
            lateral_error = _lateral_wall_error(reading)
            heading_error = _wrap_angle(theta_target - self.pose.theta_rad)

            omega = pid.update(lateral_error, self.dt) * 0.01 + 0.6 * heading_error
            omega += self.rng.gauss(0.0, self.drive.omega_noise_std)
            omega = _clip(omega, -self.drive.max_omega_rad_s, self.drive.max_omega_rad_s)

            self.pose.x_mm += v * math.cos(self.pose.theta_rad) * self.dt
            self.pose.y_mm += v * math.sin(self.pose.theta_rad) * self.dt
            self.pose.theta_rad = _wrap_angle(self.pose.theta_rad + omega * self.dt)

            w_left, w_right = self.drive.wheel_angular_speeds(v, omega)
            self.total_left_ticks += self.drive.ticks_for(w_left, self.dt)
            self.total_right_ticks += self.drive.ticks_for(w_right, self.dt)

            if self._check_collision(maze, cell_size_mm):
                collided = True
                self.collisions += 1
                break

        ideal_x = start_x + math.cos(theta_target) * cell_size_mm
        ideal_y = start_y + math.sin(theta_target) * cell_size_mm
        lateral_drift = _point_to_line_distance(self.pose.x_mm, self.pose.y_mm, start_x, start_y, ideal_x, ideal_y)
        heading_error_deg = math.degrees(_wrap_angle(theta_target - self.pose.theta_rad))

        return {
            "collided": collided,
            "lateral_drift_mm": lateral_drift,
            "heading_error_deg": heading_error_deg,
            "final_pose": (self.pose.x_mm, self.pose.y_mm, math.degrees(self.pose.theta_rad)),
        }

    def turn_90_physics(self, direction: str, n_steps: int = 25) -> Dict:
        """
        Rotate in place using a trapezoidal angular-velocity profile
        (+/-90 degrees for 'left'/'right', 180 degrees for 'back'), then
        apply a single closed-loop correction pass (as a gyro-equipped
        real robot would) before reporting the residual heading error.
        """
        turn_angle_deg = {"left": -90.0, "right": 90.0, "back": 180.0}[direction]
        theta_start = self.pose.theta_rad
        theta_target = _wrap_angle(theta_start + math.radians(turn_angle_deg))
        sign = 1.0 if turn_angle_deg > 0 else -1.0

        omega_profile = _trapezoidal_profile(n_steps, math.radians(abs(turn_angle_deg)), self.dt)
        for omega_mag in omega_profile:
            omega = sign * omega_mag + self.rng.gauss(0.0, self.drive.omega_noise_std)
            self.pose.theta_rad = _wrap_angle(self.pose.theta_rad + omega * self.dt)
            w_left, w_right = self.drive.wheel_angular_speeds(0.0, omega)
            self.total_left_ticks += self.drive.ticks_for(w_left, self.dt)
            self.total_right_ticks += self.drive.ticks_for(w_right, self.dt)


        residual = _wrap_angle(theta_target - self.pose.theta_rad)
        self.pose.theta_rad = _wrap_angle(
            self.pose.theta_rad + 0.8 * residual + self.rng.gauss(0.0, self.drive.omega_noise_std * self.dt)
        )

        heading_error_deg = math.degrees(_wrap_angle(theta_target - self.pose.theta_rad))
        return {
            "heading_error_deg": heading_error_deg,
            "final_theta_deg": math.degrees(self.pose.theta_rad),
        }



# 12. NOISY MICROMOUSE -- SAME API, REALISTIC EXECUTION UNDERNEATH

class NoisyMicromouse(Micromouse):


    def __init__(
        self,
        maze_size: int,
        start: Tuple[int, int],
        start_heading: str,
        goal_cells: Set[Tuple[int, int]],
        drive_config: Optional[DifferentialDriveConfig] = None,
        sensor_sigma_mm: float = 6.0,
        robot_radius_mm: float = 40.0,
        dt_s: float = 0.01,
        seed: Optional[int] = None,
    ):
        super().__init__(maze_size, start, start_heading, goal_cells)
        rng = random.Random(seed)
        pose = pose_for_cell(start[0], start[1], start_heading, CELL_SIZE_MM)
        drive = DifferentialDrive(drive_config)
        sensors = NoisySensorArray(sigma_mm=sensor_sigma_mm, rng=rng)
        self.physics = RobotPhysics(pose=pose, drive=drive, sensors=sensors,
                                     robot_radius_mm=robot_radius_mm, dt_s=dt_s, rng=rng)
        self.true_maze: Optional[Maze] = None
        self.drift_log: List[Dict] = []
        self.collision_count: int = 0

    def sense_walls(self, true_maze: Maze) -> Dict[str, bool]:
        self.true_maze = true_maze
        reading = self.physics.sensors.read(self.physics.pose, true_maze, CELL_SIZE_MM)
        result = {"front": reading["front_wall"], "left": reading["left_wall"], "right": reading["right_wall"]}
        for rel, direction in self._relative_directions().items():
            if result[rel]:
                self._record_wall(direction)
        return result

    def move_forward(self) -> None:
        r, c = self.position
        if self.known_walls[r, c] & DIR_BIT[self.heading]:
            raise IllegalMoveError(f"Wall ahead at {self.position} facing {self.heading}")
        if self.true_maze is None:

            return super().move_forward()

        result = self.physics.forward_one_cell_physics(self.true_maze, target_heading=self.heading)
        self.drift_log.append(result)
        if result["collided"]:
            self.collision_count += 1

        dr, dc = DELTA[self.heading]
        nr, nc = r + dr, c + dc
        if not (0 <= nr < self.size and 0 <= nc < self.size):
            raise IllegalMoveError("Attempted to move outside the maze boundary")
        self.position = (nr, nc)
        self.visited.add(self.position)
        self.physics.pose = pose_for_cell(nr, nc, self.heading, CELL_SIZE_MM)
        self.history.append({"position": self.position, "heading": self.heading})

    def _physics_turn(self, direction_key: str, grid_turn_fn) -> None:
        result = self.physics.turn_90_physics(direction_key)
        self.drift_log.append(result)
        grid_turn_fn()
        self.physics.pose.theta_rad = math.radians(HEADING_TO_THETA_DEG[self.heading])

    def turn_left(self) -> None:
        self._physics_turn("left", super().turn_left)

    def turn_right(self) -> None:
        self._physics_turn("right", super().turn_right)

    def turn_back(self) -> None:
        self._physics_turn("back", super().turn_back)



# 13. DRIFT ANALYSIS FUNCTIONS

def test_straight_line_drift(runs: int = 100, seed: Optional[int] = None, verbose: bool = True, **physics_kwargs) -> Dict:

    rng = random.Random(seed)


    maze = Maze(size=5)
    maze.walls[:, :] = WALL_N | WALL_E | WALL_S | WALL_W
    for row in (1, 2, 3):
        maze._remove_wall((row, 2), "N")

    drifts, headings = [], []
    for _ in range(runs):
        trial_rng = random.Random(rng.randint(0, 10**9))
        pose = pose_for_cell(3, 2, "N", CELL_SIZE_MM)
        physics = RobotPhysics(pose=pose, rng=trial_rng, **physics_kwargs)
        result = physics.forward_one_cell_physics(maze, target_heading="N")
        drifts.append(abs(result["lateral_drift_mm"]))
        headings.append(abs(result["heading_error_deg"]))

    summary = {
        "runs": runs,
        "avg_drift_mm": float(np.mean(drifts)),
        "max_drift_mm": float(np.max(drifts)),
        "avg_heading_error_deg": float(np.mean(headings)),
        "max_heading_error_deg": float(np.max(headings)),
    }
    if verbose:
        print("\n===== test_straight_line_drift =====")
        for k, v in summary.items():
            print(f"{k}: {v}")
        print("=====================================\n")
    return summary


def test_turn_drift(runs: int = 100, seed: Optional[int] = None, verbose: bool = True, **physics_kwargs) -> Dict:

    rng = random.Random(seed)
    errors = []
    for _ in range(runs):
        trial_rng = random.Random(rng.randint(0, 10**9))
        pose = RobotPose(x_mm=CELL_SIZE_MM * 2.5, y_mm=CELL_SIZE_MM * 2.5, theta_rad=0.0)
        physics = RobotPhysics(pose=pose, rng=trial_rng, **physics_kwargs)
        direction = trial_rng.choice(["left", "right"])
        result = physics.turn_90_physics(direction)
        errors.append(abs(result["heading_error_deg"]))

    summary = {
        "runs": runs,
        "avg_heading_error_deg": float(np.mean(errors)),
        "max_heading_error_deg": float(np.max(errors)),
    }
    if verbose:
        print("\n===== test_turn_drift =====")
        for k, v in summary.items():
            print(f"{k}: {v}")
        print("============================\n")
    return summary


def test_noisy_maze_solving(
    num_mazes: int = 20, size: int = 16, seed: Optional[int] = None,
    max_steps: int = 5000, verbose: bool = True, **physics_kwargs,
) -> Dict:
    """
    Runs the *unmodified* Flood Fill exploration + speed-run pipeline on
    `num_mazes` unseen random mazes with the Version 2 physics + noisy
    sensors enabled, to validate the algorithm still reliably solves the
    maze when motion and sensing are no longer perfect.
    """
    rng = random.Random(seed)
    successes = 0
    collisions_total = 0
    drift_samples: List[float] = []
    heading_samples: List[float] = []

    for i in range(num_mazes):
        maze_seed = rng.randint(0, 10**9)
        sim = Simulator(
            random_maze=True, size=size, seed=maze_seed,
            physics=True, physics_seed=rng.randint(0, 10**9), **physics_kwargs,
        )
        ok = sim.run_exploration(max_steps=max_steps, verbose=False)
        if ok:
            sim.run_speed_run(verbose=False)
            successes += 1

        collisions_total += sim.mouse.collision_count
        for rec in sim.mouse.drift_log:
            if "lateral_drift_mm" in rec:
                drift_samples.append(abs(rec["lateral_drift_mm"]))
            if "heading_error_deg" in rec:
                heading_samples.append(abs(rec["heading_error_deg"]))

        if verbose and (i + 1) % 5 == 0:
            print(f"  [{i + 1}/{num_mazes}] cumulative successes: {successes}")

    summary = {
        "num_mazes": num_mazes,
        "success_rate": successes / num_mazes if num_mazes else 0.0,
        "total_collisions": collisions_total,
        "avg_drift_mm": float(np.mean(drift_samples)) if drift_samples else None,
        "avg_heading_error_deg": float(np.mean(heading_samples)) if heading_samples else None,
    }
    if verbose:
        print("\n===== test_noisy_maze_solving (Version 2 validation) =====")
        for k, v in summary.items():
            print(f"{k}: {v}")
        print("============================================================\n")
    return summary



MAZE_CHOICES_V2: List[str] = ["random", "easy", "medium", "hard"]


def get_demo_maze_v2(name: str, size: int = 16) -> Maze:
    """Small set of fixed, hand-authored 16x16 mazes (easy/medium/hard) for
    repeatable demos and regression checks, alongside `random`."""
    if size != 16:
        raise ValueError("get_demo_maze_v2 only supports size=16 for now.")
    maze = Maze(size)
    maze.walls[:, :] = WALL_N | WALL_E | WALL_S | WALL_W
    maze._add_border_walls()

    paths = {
        "easy": [
            (15, 0), (14, 0), (13, 0), (12, 0), (11, 0), (10, 0), (9, 0), (8, 0),
            (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7),
        ],
        "medium": [
            (15, 0), (14, 0), (13, 0), (12, 0), (11, 0),
            (11, 1), (11, 2), (11, 3), (11, 4),
            (10, 4), (9, 4), (8, 4), (7, 4),
            (7, 5), (7, 6), (7, 7),
        ],
        "hard": [
            (15, 0), (14, 0), (13, 0),
            (13, 1), (13, 2), (13, 3),
            (12, 3), (11, 3), (10, 3), (9, 3),
            (9, 2), (9, 1),
            (8, 1), (7, 1),
            (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7),
        ],
    }
    if name not in paths:
        raise ValueError(f"Unknown maze name: {name!r}; pick one of {list(paths)}")

    path = paths[name]
    for i in range(len(path) - 1):
        r1, c1 = path[i]
        r2, c2 = path[i + 1]
        dr, dc = r2 - r1, c2 - c1
        for d in DIR_ORDER:
            if DELTA[d] == (dr, dc):
                maze._remove_wall((r1, c1), d)
                break
    return maze


def build_simulator_v2(
    maze_choice: str = "random",
    size: int = 16,
    seed: Optional[int] = None,
    loop_factor: float = 0.03,
    physics: bool = False,
    physics_seed: Optional[int] = None,
    sensor_sigma_mm: float = 6.0,
    robot_radius_mm: float = 40.0,
    dt_s: float = 0.01,
) -> Simulator:
    """Create a Simulator for a named maze choice, in ideal or physics mode.
    """
    choice = maze_choice.lower().strip()
    if choice not in MAZE_CHOICES_V2:
        raise ValueError(f"Unknown maze_choice {maze_choice!r}; pick one of {MAZE_CHOICES_V2}")

    physics_kwargs = dict(
        physics=physics, physics_seed=physics_seed, sensor_sigma_mm=sensor_sigma_mm,
        robot_radius_mm=robot_radius_mm, dt_s=dt_s,
    )

    if choice == "random":
        return Simulator(random_maze=True, size=size, seed=seed, loop_factor=loop_factor, **physics_kwargs)

    maze = get_demo_maze_v2(choice, size=size)
    return Simulator(maze=maze, **physics_kwargs)

maze_choice = "random"  # @param ["random", "easy", "medium", "hard"]
physics = True          # @param {type:"boolean"}
seed = 42                # @param {type:"integer"}
physics_seed = 7         # @param {type:"integer"}

sim = build_simulator_v2(maze_choice, seed=seed, physics=physics, physics_seed=physics_seed)
sim.run_exploration()
sim.run_speed_run()
sim.report()

sim.animate(interval=200)

bench = Benchmark(size=16, seed=1)
bench.run_benchmark(num_mazes=100)

test_straight_line_drift(runs=100, seed=1)
test_turn_drift(runs=100, seed=1)
test_noisy_maze_solving(num_mazes=20, seed=2)